repos:
    - owner: GuizhanCraft
      repo: InfinityExpansion2
      branch: master
      folder: InfinityExpansion2
      files:
          - source: "src/main/resources/lang/en.yml"
            name: "en-US.yml"
            target: "src/main/resources/lang/{lang}.yml"
    - owner: GuizhanCraft
      repo: RebarMobs
      branch: master
      folder: RebarMobs
      language_mapping:
          zh_CN: zh-CN
          zh_TW: zh-TW
      files:
          - source: "src/main/resources/lang/en.yml"
            name: "en-US.yml"
            target: "src/main/resources/lang/{lang}.yml"
