[project]
name = "script"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["ruamel.yaml"]

[project.scripts]
script = "script:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
